import "server-only";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { all, get, update } from "./db";
import { now, sha256 } from "./ids";
import { readFile } from "./storage";
import { addVersion, type DocumentRow, type VersionRow } from "./documents";
import { logActivity, notifyWorkspace } from "./activity";
import { sendMail, appUrl } from "./mail";

export type SignatureRequestRow = {
  id: string;
  workspace_id: string;
  document_id: string;
  version_id: string;
  title: string;
  message: string;
  status: string;
  sequential: number;
  created_by: string;
  created_at: number;
  sent_at: number | null;
  completed_at: number | null;
  signed_version_id: string | null;
};

export type SignerRow = {
  id: string;
  request_id: string;
  name: string;
  email: string;
  order_index: number;
  token: string;
  status: string;
  viewed_at: number | null;
  signed_at: number | null;
  ip: string | null;
  user_agent: string | null;
  signature_png: string | null;
  decline_reason: string | null;
  last_reminded_at: number | null;
};

export type FieldRow = {
  id: string;
  request_id: string;
  signer_id: string;
  page: number;
  x: number;
  y: number;
  w: number;
  h: number;
  kind: "signature" | "initials" | "date" | "name" | "text";
  value: string | null;
};

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const b64 = dataUrl.split(",")[1] ?? "";
  return Uint8Array.from(Buffer.from(b64, "base64"));
}

const fmtTime = (t: number | null) => (t ? new Date(t).toISOString().replace("T", " ").slice(0, 19) + " UTC" : "—");

/** Stamps every signer's fields onto the original version and appends an audit certificate page. */
export async function finalizeSignature(req: SignatureRequestRow) {
  const version = get<VersionRow>("SELECT * FROM document_versions WHERE id = ?", req.version_id)!;
  const original = await readFile(version.storage_key);
  const pdf = await PDFDocument.load(original, { updateMetadata: false });
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const signers = all<SignerRow>("SELECT * FROM signers WHERE request_id = ? ORDER BY order_index", req.id);
  const fields = all<FieldRow>("SELECT * FROM signature_fields WHERE request_id = ?", req.id);
  const pages = pdf.getPages();

  for (const f of fields) {
    const signer = signers.find((s) => s.id === f.signer_id);
    const page = pages[f.page - 1];
    if (!signer || !page) continue;
    const { width, height } = page.getSize();
    const x = f.x * width;
    const w = f.w * width;
    const h = f.h * height;
    const y = height - f.y * height - h;
    if ((f.kind === "signature" || f.kind === "initials") && (f.value || signer.signature_png)) {
      const src = f.kind === "initials" && f.value?.startsWith("data:") ? f.value : signer.signature_png!;
      const img = await pdf.embedPng(dataUrlToBytes(src));
      const s = Math.min(w / img.width, h / img.height);
      page.drawImage(img, { x: x + (w - img.width * s) / 2, y: y + (h - img.height * s) / 2, width: img.width * s, height: img.height * s });
      page.drawLine({ start: { x, y }, end: { x: x + w, y }, thickness: 0.5, color: rgb(0.55, 0.55, 0.55) });
      page.drawText(`pdftek ${signer.id.slice(-8)}`, { x, y: y - 7, size: 5, font, color: rgb(0.55, 0.55, 0.55) });
    } else {
      const text =
        f.kind === "date" ? new Date(signer.signed_at ?? now()).toISOString().slice(0, 10) : f.kind === "name" ? signer.name : (f.value ?? "");
      const size = Math.max(6, Math.min(12, h * 0.6));
      page.drawText(text, { x: x + 2, y: y + (h - size) / 2 + 1, size, font, color: rgb(0.05, 0.1, 0.25), maxWidth: w - 4 });
    }
  }

  // Audit certificate
  const cert = pdf.addPage([612, 792]);
  let cy = 740;
  const line = (label: string, value: string, opts: { size?: number; b?: boolean } = {}) => {
    cert.drawText(label, { x: 56, y: cy, size: 9, font: bold, color: rgb(0.35, 0.35, 0.35) });
    cert.drawText(value, { x: 200, y: cy, size: opts.size ?? 9, font: opts.b ? bold : font, color: rgb(0.1, 0.1, 0.1), maxWidth: 356 });
    cy -= 16;
  };
  cert.drawText("Certificate of completion", { x: 56, y: cy, size: 20, font: bold, color: rgb(0.06, 0.08, 0.11) });
  cy -= 22;
  cert.drawText("Electronic signature audit trail generated by pdftek", { x: 56, y: cy, size: 10, font, color: rgb(0.45, 0.45, 0.45) });
  cy -= 34;
  line("Envelope", req.id);
  line("Title", req.title);
  line("Original SHA-256", version.sha256.slice(0, 64), { size: 7.5 });
  line("Sent", fmtTime(req.sent_at));
  line("Completed", fmtTime(now()));
  cy -= 14;
  for (const s of signers) {
    cert.drawRectangle({ x: 48, y: cy - 86, width: 516, height: 100, color: rgb(0.97, 0.96, 0.93) });
    cy -= 2;
    line("Signer", `${s.name} <${s.email}>`, { b: true });
    line("Viewed", fmtTime(s.viewed_at));
    line("Signed", fmtTime(s.signed_at));
    line("IP address", s.ip ?? "—");
    line("User agent", (s.user_agent ?? "—").slice(0, 90), { size: 7 });
    if (s.signature_png) {
      const img = await pdf.embedPng(dataUrlToBytes(s.signature_png));
      const sc = Math.min(120 / img.width, 36 / img.height);
      cert.drawImage(img, { x: 430, y: cy + 36, width: img.width * sc, height: img.height * sc });
    }
    cy -= 26;
  }
  cert.drawText(
    "Each signer authenticated via a unique link sent to their email address and agreed to sign electronically.",
    { x: 56, y: 60, size: 8, font, color: rgb(0.45, 0.45, 0.45), maxWidth: 500 },
  );

  pdf.setModificationDate(new Date());
  const bytes = Buffer.from(await pdf.save());
  const doc = get<DocumentRow>("SELECT * FROM documents WHERE id = ?", req.document_id)!;
  const signedVersion = await addVersion({ doc, userId: req.created_by, pdf: bytes, note: `Signed — ${req.title}` });
  update("signature_requests", req.id, { status: "completed", completed_at: now(), signed_version_id: signedVersion.id });

  logActivity({ workspaceId: req.workspace_id, actorLabel: "pdftek e-sign", action: "signature_completed", documentId: req.document_id, meta: { title: req.title } });
  notifyWorkspace(req.workspace_id, { title: `Fully signed: ${req.title}`, body: `All ${signers.length} signer(s) have signed.`, link: `/app/${req.workspace_id}?doc=${req.document_id}` });
  for (const s of signers) {
    await sendMail({
      to: s.email,
      subject: `Completed: ${req.title}`,
      heading: `${req.title} is fully signed`,
      paragraphs: [`All parties have signed. Download the final copy (with audit certificate) using the link below.`, `Document fingerprint (SHA-256): ${sha256(bytes)}`],
      cta: { label: "Download signed PDF", url: appUrl(`/sign/${s.token}`) },
    });
  }
  import("./automations").then((m) =>
    m.onEvent("signature_completed", { workspaceId: req.workspace_id, documentId: req.document_id, headline: `${req.title} fully signed`, lines: signers.map((s) => `${s.name} signed ${fmtTime(s.signed_at)}`) }),
  ).catch((e) => console.error(e));
}

export async function inviteSigner(req: SignatureRequestRow, s: SignerRow, fromName: string, reminder = false) {
  return sendMail({
    to: s.email,
    subject: `${reminder ? "Reminder: " : ""}${fromName} requested your signature: ${req.title}`,
    heading: `${reminder ? "Reminder — " : ""}Please sign “${req.title}”`,
    paragraphs: [
      `${fromName} sent you a document to review and sign electronically.`,
      ...(req.message ? [`Message: ${req.message}`] : []),
      "The link below is unique to you — don't forward it.",
    ],
    cta: { label: "Review & sign", url: appUrl(`/sign/${s.token}`) },
  });
}
